# TCL File Generated by Component Editor 13.1
# Wed Mar 04 13:34:17 EST 2015
# DO NOT MODIFY


# 
# bcon_input "bcon_input" v1.0
#  2015.03.04.13:34:17
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module bcon_input
# 
set_module_property DESCRIPTION "Input data via Basler BCON LVDS Protocol."
set_module_property NAME bcon_input
set_module_property VERSION 1.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME bcon_input
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL bcon_input
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file bcon_input.vhd VHDL PATH bcon_input.vhd TOP_LEVEL_FILE
add_fileset_file bcon_input.sdc SDC PATH bcon_input.sdc
add_fileset_file altlvdsrx_5x7.qip OTHER PATH altlvdsrx_5x7.qip
add_fileset_file pll_1x7_reconfig.qip OTHER PATH pll_1x7_reconfig.qip
add_fileset_file altlvdsrx_5x7.vhd VHDL PATH altlvdsrx_5x7.vhd
add_fileset_file trig_gen_pkg.vhd VHDL PATH trig_gen_pkg.vhd
add_fileset_file bcon_pkg.vhd VHDL PATH bcon_pkg.vhd
add_fileset_file trigger_generator.vhd VHDL PATH trigger_generator.vhd
add_fileset_file pll_1x7_reconfig.vhd VHDL PATH pll_1x7_reconfig.vhd
add_fileset_file pll_1x7_reconfig/pll_1x7_reconfig_0002.v VERILOG PATH pll_1x7_reconfig/pll_1x7_reconfig_0002.v
add_fileset_file pll_1x7_reconfig/pll_1x7_reconfig_0002.qip OTHER PATH pll_1x7_reconfig/pll_1x7_reconfig_0002.qip

# 
# parameters
# 
add_parameter g_lane_invert STD_LOGIC_VECTOR 0
set_parameter_property g_lane_invert DEFAULT_VALUE 0
set_parameter_property g_lane_invert DISPLAY_NAME "BCON Link Lane Invert vector 1F (XX)"
set_parameter_property g_lane_invert TYPE STD_LOGIC_VECTOR
set_parameter_property g_lane_invert UNITS None
set_parameter_property g_lane_invert ALLOWED_RANGES 0:31
set_parameter_property g_lane_invert DESCRIPTION "Inverts BCON link lanes.  Bits 4-0 X3..X0..XCLK"
set_parameter_property g_lane_invert HDL_PARAMETER true

# 
# display items
# 

# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock register_clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset i_rst reset Input 1



# 
# connection point register_access
# 
add_interface register_access avalon end
set_interface_property register_access addressUnits WORDS
set_interface_property register_access associatedClock register_clock
set_interface_property register_access associatedReset reset
set_interface_property register_access bitsPerSymbol 8
set_interface_property register_access burstOnBurstBoundariesOnly false
set_interface_property register_access burstcountUnits WORDS
set_interface_property register_access explicitAddressSpan 0
set_interface_property register_access holdTime 0
set_interface_property register_access linewrapBursts false
set_interface_property register_access maximumPendingReadTransactions 0
set_interface_property register_access readLatency 1
set_interface_property register_access readWaitTime 1
set_interface_property register_access setupTime 0
set_interface_property register_access timingUnits Cycles
set_interface_property register_access writeWaitTime 0
set_interface_property register_access ENABLED true
set_interface_property register_access EXPORT_OF ""
set_interface_property register_access PORT_NAME_MAP ""
set_interface_property register_access CMSIS_SVD_VARIABLES ""
set_interface_property register_access SVD_ADDRESS_GROUP ""

add_interface_port register_access i_reg_addr address Input 5
add_interface_port register_access i_reg_read_en read Input 1
add_interface_port register_access i_reg_write_en write Input 1
add_interface_port register_access i_reg_writedata writedata Input 32
add_interface_port register_access o_reg_readdata readdata Output 32
add_interface_port register_access o_reg_waitrequest waitrequest Output 1
set_interface_assignment register_access embeddedsw.configuration.isFlash 0
set_interface_assignment register_access embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment register_access embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment register_access embeddedsw.configuration.isPrintableDevice 0


# 
# connection point register_clock
# 
add_interface register_clock clock end
set_interface_property register_clock clockRate 0
set_interface_property register_clock ENABLED true
set_interface_property register_clock EXPORT_OF ""
set_interface_property register_clock PORT_NAME_MAP ""
set_interface_property register_clock CMSIS_SVD_VARIABLES ""
set_interface_property register_clock SVD_ADDRESS_GROUP ""

add_interface_port register_clock i_register_clock clk Input 1


# 
# connection point pixel_clock
# 
add_interface pixel_clock clock start
set_interface_property pixel_clock clockRate 0
set_interface_property pixel_clock ENABLED true
set_interface_property pixel_clock EXPORT_OF ""
set_interface_property pixel_clock PORT_NAME_MAP ""
set_interface_property pixel_clock CMSIS_SVD_VARIABLES ""
set_interface_property pixel_clock SVD_ADDRESS_GROUP ""

add_interface_port pixel_clock o_pixel_clock clk Output 1

# 
# connection point data_clock
# 
add_interface data_clock clock end
set_interface_property data_clock clockRate 0
set_interface_property data_clock ENABLED true
set_interface_property data_clock EXPORT_OF ""
set_interface_property data_clock PORT_NAME_MAP ""
set_interface_property data_clock CMSIS_SVD_VARIABLES ""
set_interface_property data_clock SVD_ADDRESS_GROUP ""

add_interface_port data_clock i_data_clock clk Input 1

# 
# connection point data_out
# 
add_interface data_out avalon_streaming start
set_interface_property data_out associatedClock data_clock
set_interface_property data_out associatedReset reset
set_interface_property data_out dataBitsPerSymbol 8
set_interface_property data_out errorDescriptor ""
set_interface_property data_out firstSymbolInHighOrderBits true
set_interface_property data_out maxChannel 0
set_interface_property data_out readyLatency 0
set_interface_property data_out ENABLED true
set_interface_property data_out EXPORT_OF ""
set_interface_property data_out PORT_NAME_MAP ""
set_interface_property data_out CMSIS_SVD_VARIABLES ""
set_interface_property data_out SVD_ADDRESS_GROUP ""

add_interface_port data_out o_data_out_data data Output 32
add_interface_port data_out o_data_out_valid valid Output 1
add_interface_port data_out o_data_out_endofpacket endofpacket Output 1
add_interface_port data_out o_data_out_startofpacket startofpacket Output 1
add_interface_port data_out i_data_out_ready ready Input 1

# 
# connection point timestamp_latch_out
# 
add_interface timestamp_latch_out conduit end
set_interface_property timestamp_latch_out associatedClock data_clock
set_interface_property timestamp_latch_out ENABLED true
set_interface_property timestamp_latch_out EXPORT_OF ""
set_interface_property timestamp_latch_out PORT_NAME_MAP ""
set_interface_property timestamp_latch_out CMSIS_SVD_VARIABLES ""
set_interface_property timestamp_latch_out SVD_ADDRESS_GROUP ""

add_interface_port timestamp_latch_out o_stamp_latch stamp_latch Output 1
add_interface_port timestamp_latch_out o_stamp_marker stamp_marker Output 32
 
# 
# connection point timestamp_in
# 
add_interface timestamp_in conduit end
set_interface_property timestamp_in associatedClock data_clock
set_interface_property timestamp_in ENABLED true
set_interface_property timestamp_in EXPORT_OF ""
set_interface_property timestamp_in PORT_NAME_MAP ""
set_interface_property timestamp_in CMSIS_SVD_VARIABLES ""
set_interface_property timestamp_in SVD_ADDRESS_GROUP ""

add_interface_port timestamp_in i_timestamp stamp_timestamp Input 32
add_interface_port timestamp_in i_timestamp_slow stamp_timestamp_slow Input 32

# 
# connection point bcon_bm_interface
# 
add_interface bcon_bm_interface conduit end
set_interface_property bcon_bm_interface associatedClock ""
set_interface_property bcon_bm_interface associatedReset ""
set_interface_property bcon_bm_interface ENABLED true
set_interface_property bcon_bm_interface EXPORT_OF ""
set_interface_property bcon_bm_interface PORT_NAME_MAP ""
set_interface_property bcon_bm_interface CMSIS_SVD_VARIABLES ""
set_interface_property bcon_bm_interface SVD_ADDRESS_GROUP ""

add_interface_port bcon_bm_interface i_bcon_x export Input 4
add_interface_port bcon_bm_interface i_bcon_xclk export Input 1
add_interface_port bcon_bm_interface o_bcon_cc export Output 1
add_interface_port bcon_bm_interface o_fpga_trig export Output 1

# 
#
add_interface reconfig_to_pll conduit end
set_interface_property reconfig_to_pll associatedClock ""
set_interface_property reconfig_to_pll associatedReset ""
set_interface_property reconfig_to_pll ENABLED true

add_interface_port reconfig_to_pll reconfig_to_pll reconfig_to_pll Input 64

#
# 
#
add_interface reconfig_from_pll conduit end
set_interface_property reconfig_from_pll associatedClock ""
set_interface_property reconfig_from_pll associatedReset ""
set_interface_property reconfig_from_pll ENABLED true

add_interface_port reconfig_from_pll reconfig_from_pll reconfig_from_pll Output 64

#
#
#
add_interface video_out conduit end
set_interface_property video_out associatedClock data_clock
set_interface_property video_out associatedReset ""
set_interface_property video_out ENABLED true

add_interface_port video_out o_line_valid export Output 1
add_interface_port video_out o_frame_valid export Output 1
add_interface_port video_out o_data_valid export Output 1
add_interface_port video_out o_data export Output 24
